hard_tabs = true

max_width = 120

# fn_params_layout = "Compressed"
# use_small_heuristics = "Max"

# enum_discrim_align_threshold = 20
# struct_field_align_threshold = 20

# indent_style = "Visual"

overflow_delimited_expr = true

format_code_in_doc_comments = true
wrap_comments = true
comment_width = 80
