hard_tabs = true

# max_width = 100

# fn_args_layout = "Compressed"
# use_small_heuristics = "Max"

# enum_discrim_align_threshold = 20
# struct_field_align_threshold = 20

# indent_style = "Visual"

format_code_in_doc_comments = true
wrap_comments = true
# comment_width = 100
